[package]
edition = "2021"
name = "ui"
version = "0.1.0"

[dependencies]
anyhow = "1.0.75"
bytes = "1.5.0"
fltk = {version = "1.4.12", features = ["fltk-bundled"]}
tracing = {version = "0.1.37", features = ["log"]}
tracing-subscriber = {version = "0.3.17", features = ["env-filter"]}
engine = { path = "./lib/engine" }


[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"

[workspace]
members = ["lib/*"]
